apiVersion: v1
kind: Service
metadata:
  name:  my-app-service
  namespace: my-video-service
spec:
  type: Tomcat
  selector:
    app:  my-app-service
  ports:
  - nodePort: 30082
    port: 8080
    targetPort: 8080
